// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ocp-docs-api/internal/repo (interfaces: Repo)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	document "github.com/ocp-docs-api/internal/models/document"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AddDocs mocks base method.
func (m *MockRepo) AddDocs(arg0 []document.Document) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDocs", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDocs indicates an expected call of AddDocs.
func (mr *MockRepoMockRecorder) AddDocs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDocs", reflect.TypeOf((*MockRepo)(nil).AddDocs), arg0)
}
